"use strict";
exports.__esModule = true;
var FacA_1 = require("./FacA");
var FacB_1 = require("./FacB");
var fa = new FacA_1.FacA();
fa.pordEngine();
fa.prodAircon();
var fb = new FacB_1.FacB();
fb.pordEngine();
fb.prodAircon();
